server:
  port: 8090
spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5430/demoDB
#    username: usr
#    password: pwd

services:
  clientService: inmemory

logging:
  level:
    root: ERROR
    ru.otus: DEBUG