server:
  port: 8080
services:
  #clientService: inmemory
  clientService: jdbc

api:
  rest-api-prefix: /api
  rest-api-version: v1

logging:
  level:
    #root: DEBUG
    root: ERROR
    ru.otus: DEBUG
    #com.zaxxer.hikari.HikariConfig: DEBUG
    org.flywaydb: INFO
    org.springframework.jdbc.core.JdbcTemplate: TRACE

spring:
  jackson:
    serialization:
      indent_output: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    #url: jdbc:postgresql://localhost:5430/demoDB
    jdbc-url: jdbc:postgresql://localhost:5430/demoDB
    driver-class-name: org.postgresql.Driver
    username: usr
    password: pwd


springdoc:
  swagger-ui:
    path: "/swagger-ui"