server:
  port: 8090
services:
  clientService: inmemory

api:
  rest-api-prefix: /api
  rest-api-version: v1

logging:
  level:
    root: ERROR
    ru.otus: DEBUG

spring:
  jackson:
    serialization:
      indent_output: true

springdoc:
  swagger-ui:
    path: "/swagger-ui"